Repository openpubkey/opkssh, pull requests merged in 2025-05, with the labels that each got.

#179 Documents how to use PuTTY with opkssh
  README.md
  docs/putty.md
Labels: documentation

#181 Creates policy plugin system (env vars)
  README.md
  commands/add_test.go
  commands/verify.go
  commands/verify_test.go
  docs/config.md
  docs/policyplugins.md
  go.mod
  policy/enforcer.go
  policy/enforcer_test.go
  policy/files/fileloader.go
  policy/files/permschecker.go
  policy/files/permschecker_test.go
  policy/plugins/pluginconfig.go
  policy/plugins/plugins.go
  policy/plugins/plugins_test.go
  policy/plugins/tokens.go
  policy/plugins/tokens_test.go
  scripts/install-linux.sh
  test/integration/policy-plugins/plugin-cmd.sh
  test/integration/policy-plugins/plugin-simple.yml
  test/integration/ssh_test.go
Labels: enhancement

#185 docs: Clarify point in policy plugin docs
  docs/policyplugins.md
Labels: documentation, chore

#189 Creates server config.yml to set env variables
  commands/config/client_config.go
  commands/config/client_config_test.go
  commands/config/default-client-config.yml
  commands/config/providerconfig.go
  commands/config/providerconfig_test.go
  commands/config/server_config.go
  commands/login.go
  commands/login_test.go
  commands/verify.go
  commands/verify_test.go
  docs/config.md
  main.go
  main_test.go
  scripts/install-linux.sh
Labels: enhancement

#190 Fix typo in README
  README.md
Labels: bug, documentation, chore

#192 Sets permissions for directories we create on install
  scripts/install-linux.sh
Labels: chore

#193 Moves off of bastionzero oidc fork
  test/integration/provider/exampleop.Dockerfile
Labels: chore

#196 Cleans up more info in the README
  README.md
Labels: chore

#197 Honor the INSTALL_DIR Variable and openSUSE/SLES support
  .github/workflows/ci.yml
  README.md
  scripts/install-linux.sh
  test/integration/ssh_server/opensuse_opkssh.Dockerfile
  test/integration/ssh_server/ssh_server.go
Labels: enhancement

#202 Add hello provider
  scripts/install-linux.sh
Labels: bug

#183 Userinfo claims support via an Access token in the ssh cert
  commands/config/client_config.go
  commands/config/client_config_test.go
  commands/config/providerconfig.go
  commands/login.go
  commands/login_test.go
  commands/verify.go
  commands/verify_test.go
  docs/config.md
  docs/policyplugins.md
  flake.nix
  go.mod
  go.sum
  main.go
  policy/enforcer.go
  policy/enforcer_test.go
  policy/plugins/plugins.go
  policy/plugins/plugins_test.go
  policy/plugins/tokens.go
  policy/plugins/tokens_test.go
  sshcert/sshcert.go
  sshcert/sshcert_test.go
  test/integration/ssh_test.go
Labels: enhancement

#215 fix: read send_access_token when parsing config
  commands/config/client_config_test.go
  commands/config/providerconfig.go
Labels: bug
