Repository openpubkey/opkssh, pull requests merged in 2025-04, with the labels that each got.

#90 Updates config documentation with recently added configuration options
  docs/config.md
Labels: documentation

#91 Silences help when hitting an error in argparser
  main.go
Labels: bug

#70 Add winget install to Readme
  README.md
Labels: enhancement

#98 feat: Adds flag to print id_token contents on login
  commands/login.go
  main.go
  test/integration/login_test.go
  test/integration/ssh_test.go
Labels: enhancement

#79 Add support for Arch Linux
  .github/workflows/ci.yml
  README.md
  scripts/install-linux.sh
  scripts/installing.md
  test/integration/ssh_server/arch_opkssh.Dockerfile
  test/integration/ssh_server/ssh_server.go
Labels: enhancement

#118 Adds details on required redirectURIs
  README.md
Labels: documentation, chore

#121 Adds security note on using a new client ID for opkssh
  README.md
Labels: documentation, chore

#60 Adding a client configuration file, allowing for easier use with custom OIDC providers
  .github/workflows/ci.yml
  README.md
  commands/login.go
  main.go
  main_test.go
Labels: enhancement

#127 Increases README clarity
  README.md
Labels: documentation

#128 bug: Removes reference to opksshrc in docs
  README.md
  main.go
Labels: bug, documentation

#116 Installation script: Create new configuration file with higher priority if needed
  scripts/install-linux.sh
  scripts/installing.md
  test/integration/ssh_server/arch_opkssh.Dockerfile
Labels: enhancement

#136 Add support for hello.coop OP
  README.md
  commands/login.go
  commands/login_test.go
  main.go
Labels: enhancement

#139 bug: Fixes release drafter
  .github/workflows/release-drafter.yml
Labels: bug

#147 doc:Add scopes example to readme
  README.md
Labels: documentation, chore

#148 Adds link to openpubkey mailing list
  README.md
Labels: documentation, chore

#143 Creates yaml client config
  README.md
  commands/client-config/config.go
  commands/client-config/config_test.go
  commands/client-config/default-client-config.yml
  commands/client-config/providerconfig.go
  commands/client-config/providerconfig_test.go
  commands/login.go
  commands/login_test.go
  go.mod
  go.sum
  main.go
  main_test.go
Labels: enhancement

#155 Switch to using standardOp customer providers
  commands/client-config/providerconfig.go
  go.mod
  go.sum
Labels: enhancement

#163 Add build instructions
  .gitignore
  CONTRIBUTING.md
  README.md
  hack/build.sh
  hack/integration-tests.sh
  hack/unit-tests.sh
Labels: enhancement
