Repository openpubkey/opkssh, pull requests merged in 2025-03, with the labels that each got.

#1 bug: Gets integration tests working
  .github/workflows/ci.yml
  commands/login.go
  commands/readhome_linux.go
  commands/verify.go
  commands/verify_test.go
  internal/projectpath/projectpath.go
  policy/enforcer_test.go
  policy/multipolicyloader_test.go
  policy/policy.go
  policy/policy_test.go
  policy/policyloader_test.go
  policy/providerloader.go
  test/integration/add_test.go
  test/integration/login_test.go
  test/integration/provider/provider.go
  test/integration/ssh_server/ssh_server.go
  test/integration/ssh_test.go
Labels: bug

#9 Bug: Updates documentation fixes broken links
  CONTRIBUTING.md
  README.md
  docs/config.md
  scripts/install-linux.sh
  scripts/installing.md
Labels: bug

#11 Debugging binary release, adding darwin
  .github/workflows/release-opkssh.yml
Labels: bug

#13 Adds brew install instructions for opkssh
  README.md
Labels: documentation

#14 Improves language in readme
  README.md
Labels: documentation

#19 test: Adds simple unittests for commands
  commands/add_test.go
  commands/login_test.go
  policy/policyloader.go
Labels: enhancement

#18 Adds support for centos and redhat
  .github/workflows/ci.yml
  README.md
  main.go
  policy/policyloader.go
  scripts/install-linux.sh
  scripts/installing.md
  test/integration/add_test.go
  test/integration/ssh_server/centos_opkssh.Dockerfile
  test/integration/ssh_server/ssh_server.go
Labels: enhancement

#26 Bumps openpubkey release 0.7.2
  go.mod
  go.sum
Labels: chore

#30 Adds flag to disable home policy configuration steps in install script
  scripts/install-linux.sh
Labels: enhancement

#31 Changes email policy check to be case-insensitive
  policy/enforcer.go
  policy/enforcer_test.go
Labels: bug

#32 bug: Fixes hanging bug caused by bad handling of context
  go.mod
  go.sum
  main.go
Labels: bug

#33 Adds argument allowing users to specify their clientID and issuer
  main.go
  main_test.go
Labels: enhancement

#58 Add support for generic OpenID Connect providers
  README.md
  main.go
  main_test.go
  policy/providerloader.go
  policy/providerloader_test.go
Labels: enhancement

#55 Adds a --help flag to the opkssh
  commands/verify.go
  main.go
  main_test.go
Labels: documentation

#61 Change public key file permissions to 0644
  commands/login.go
Labels: bug

#62 Fixes bug where client secret defaulting to Google secret
  README.md
  main.go
Labels: bug

#67 Rewrites arg parser to use Cobra
  commands/add.go
  commands/add_test.go
  commands/login.go
  go.mod
  go.sum
  main.go
  main_test.go
Labels: enhancement

#71 tests: Removes dir creation from docker script to ensure add creates them in tests
  test/integration/add_test.go
  test/integration/ssh_server/centos_opkssh.Dockerfile
  test/integration/ssh_server/debian_opkssh.Dockerfile
Labels: enhancement

#74 Adds sftp to integration tests
  README.md
  commands/login.go
  test/integration/ssh_test.go
Labels: chore

#75 Fix typo in README
  README.md
Labels: documentation, chore

#76 bug: Adds login --disable-browser-open flag
  commands/login.go
  go.mod
  go.sum
  main.go
Labels: bug
